application: dragonstache
version: duby
runtime: java
public_root: /public

resource_files:
  - exclude: /build/**

handlers:
  - url: /bookmarks/*
    servlet: app.controllers.BookmarksController
    name: bookmarks
